# theme.toml template for a Hugo theme
name = "CatSiam Club"
license = "MIT"
licenselink = "https://github.com/ChainEasy/catsiam/blob/master/LICENSE"
description = "CatSiam Club is a digital token with a cat theme.  This a repurpased theme. "
homepage = "https://catsiam.club/"
tags = ['cats', 'crypto', 'NFT', 'gaming', 'creative agency', 'creative studio', 'portfolio', 'staticmania', 'responsive', 'blog', 'customizable', 'company', 'creative', 'agency template']
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive','landing-page', 'minimal', 'business', 'agency-template', 'hugo-theme', 'portfolio', 'company', 'creative', 'contact-form']
min_version = "0.58.0"

[author]
  name = "CatSiam Club"
  homepage = "https://catsiam.club/"
